name: Salesforce Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: 
  schedule:
    - cron: "30 8 * * 1-5"
env:
  SF_BASE_URL: https://login.salesforce.com/
jobs:
  test:
    env:
      SF_USERNAME: kudkan90616@agentforce.com
      SF_PASSWORD: Nish@nth1#
    runs-on: ubuntu-latest
    timeout-minutes: 60
    # strategy:
    #   matrix:
    #     shardIndex: [0, 1, 2, 3, 4]  # 5 shards
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    # - name: Run Playwright tests (Shard ${{ matrix.shardIndex }})
    #   run: npx playwright test --shard=${{ matrix.shardIndex }}/5

    - name: Output Information
      run: |
        echo "SF_USERNAME: ${{ env.SF_USERNAME }}"

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-${{ matrix.shardIndex }}
        path: playwright-report/
        retention-days: 30
