name: SwagLabs Playwright Defalut Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  SWLABS_BASE_URL: https://www.saucedemo.com/

jobs:
  test:
    environment: testing
    env:
      SWLABS_USERNAME: ${{ secrets.SWLABS_USERNAME }}
      SWLABS_PASSWORD: ${{ secrets.SWLABS_PASSWORD }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
