name: SwagLabs Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  SWLABS_BASE_URL: https://www.saucedemo.com/

jobs:
  playwright-tests:
    environment: testing
    env:
      SWLABS_USERNAME: ${{ secrets.SWLABS_USERNAME }}
      SWLABS_PASSWORD: ${{ secrets.SWLABS_PASSWORD }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests (sharded)
      run: npx playwright test --reporter=blob --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

    - name: Upload playwright report to GitHub Actions Artifacts
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-${{ matrix.shardIndex }}
        path: blob-report
        retention-days: 10

  merge-reports:
    name: Merge Playwright Reports
    if: ${{ !cancelled() }}
    needs: [playwright-tests]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Download blob reports from GitHub Actions Artifacts
      uses: actions/download-artifact@v4
      with:
        path: all-blob-reports
        pattern: playwright-report-*
        merge-multiple: true

    - name: Merge into HTML report
      run: npx playwright merge-reports --reporter html ./all-blob-reports

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: playwright-html-report--attempt-${{ github.run_attempt }}
        path: playwright-report
        retention-days: 10

  send-email-report:
    name: Send Email Report on Failure
    if: failure()
    needs: [merge-reports]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download HTML report from artifacts
      uses: actions/download-artifact@v4
      with:
        name: playwright-html-report--attempt-${{ github.run_attempt }}
        path: playwright-report

    - name: Send failure report via email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "❌ Playwright Test Failures - ${{ github.repository }}"
        to: qaautomationtester24@gmail.com
        from: GitHub Actions <${{ secrets.EMAIL_USERNAME }}>
        html_body: true
        body: |
          <h3>Some Playwright tests failed</h3>
          <p>Please review the attached HTML report.</p>
        attachments: playwright-report/index.html

        # App Password qkfi mqiw sszg kawb
        # https://myaccount.google.com/apppasswords